spring.application.name=CatchUp Platform
spring.profiles.active=dev
spring.messages.encoding=UTF-8
spring.jpa.open-in-view=false
spring.jpa.hibernate.naming.physical-strategy=com.acme.catchup.platform.shared.infrastructure.persistence.jpa.strategy.SnakeCasePhysicalNamingStrategy