name: Build and Release Spring Boot JAR

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Java 21
        uses: actions/setup-java@v4
        with:
          distribution: corretto
          java-version: 21

      - name: Compilar sin pruebas
        run: mvn clean package -DskipTests

      - name: Crear Release y subir JAR
        uses: softprops/action-gh-release@v2
        with:
          files: target/*.jar